name: Test
run-name: ${{ github.actor }} is learning GitHub Actions
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '11'
      - run: ./gradlew clean test